# Generated by Django 5.2.7 on 2025-11-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('prefecture', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('temp', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('rain', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefecture', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('ward', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weatherapp.city')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
